services:
  workspace:
    container_name: apex_captain_iac_devcon_workspace
    image: mcr.microsoft.com/devcontainers/base:noble

    environment:
      TZ: 'Asia/Seoul'
      IS_DEV_CONTAINER: true
      volumePathsToChangeOwner: ${nodeModulesVolumeContainerPath}

    env_file:
      - .env

    command: sleep infinity

    volumes:
      # Workspace Cache
      - ..:${containerWorkspaceFolder}:cached
      # Mount Local(Workstation) kubeconfig
      - $HOME/.kube/config:${containerWorkstationKubeconfigFilePath}:ro
      # Named Volume
      ## Node Modules
      - ApexCaptain.IaC.Workspace.node_modules:${nodeModulesVolumeContainerPath}

    extra_hosts:
      - 'kubernetes.docker.internal:host-gateway'

volumes:
  ApexCaptain.IaC.Workspace.node_modules:
