services:
  workspace:
    container_name: apex_captain_iac_devcon_workspace
    # Base On Ubuntu Noble
    image: mcr.microsoft.com/devcontainers/base:dev-noble

    environment:
      TZ: 'Asia/Seoul'
      IS_DEV_CONTAINER: true
      ENABLE_AUTO_SYNC: true
      DIR_PATHS_TO_CHANGE_OWNER: ${CONTAINER_NODE_MODULES_DIR_PATH} ${CONTAINER_GEMINI_CONFIG_DIR_PATH}

    env_file:
      - .env

    command: sleep infinity

    volumes:
      # Workspace Cache
      - ..:${containerWorkspaceFolder}:cached
      # Mount Secrets
      - ${HOST_SECRETS_DIR_PATH}:${CONTAINER_SECRETS_DIR_PATH}
      # Named Volume
      ## Node Modules
      - ApexCaptain.IaC.Workspace.node_modules:${CONTAINER_NODE_MODULES_DIR_PATH}
      ## Gemini  Config
      - ApexCaptain.IaC.Workspace.gemini-config:${CONTAINER_GEMINI_CONFIG_DIR_PATH}

volumes:
  ApexCaptain.IaC.Workspace.node_modules:
  ApexCaptain.IaC.Workspace.gemini-config:
