services:
  workspace:
    container_name: apex_captain_iac_devcon_workspace
    image: mcr.microsoft.com/devcontainers/base:noble

    environment:
      TZ: 'Asia/Seoul'
      IS_DEV_CONTAINER: true
      volumePathsToChangeOwner: ${CONTAINER_NODE_MODULES_DIR_PATH} ${CONTAINER_KUBE_CONFIG_DIR_PATH}

    env_file:
      - .env

    command: sleep infinity

    volumes:
      # Workspace Cache
      - ..:${containerWorkspaceFolder}:cached
      # Mount Secrets
      - ${HOST_SECRETS_DIR_PATH}:${CONTAINER_SECRETS_DIR_PATH}
      # Mount Local(Workstation) kubeconfig
      - ${HOST_WORKSTATION_KUBE_CONFIG_FILE_PATH}:${CONTAINER_WORKSTATION_KUBE_CONFIG_FILE_PATH}:ro
      # Named Volume
      ## Node Modules
      - ApexCaptain.IaC.Workspace.node_modules:${CONTAINER_NODE_MODULES_DIR_PATH}

volumes:
  ApexCaptain.IaC.Workspace.node_modules:
